"""Legacy shim — re-exports from sources.sakshi.config."""
# ruff: noqa: F401,F403

from sources.sakshi.config import *  # noqa: F401,F403
from sources.sakshi.config import (
    BASE_DIR,
    DATA_DIR,
    LOCATION_DICTIONARY_PATH,
    NON_LOCAL_URL_PATH_MARKERS,
    NON_RETRYABLE_HTTP_STATUSES,
    SAKSHI_AI_VALIDATION,
    SAKSHI_ANALYZER_OUTPUT_DIR,
    SAKSHI_ARTICLE_BODY_SELECTOR,
    SAKSHI_ARTICLE_LINK_SELECTOR,
    SAKSHI_ARTICLE_PATH,
    SAKSHI_BASE_URL,
    SAKSHI_CHECKPOINT_FILE,
    SAKSHI_CONSTITUENCY_SCORE_THRESHOLD,
    SAKSHI_ENABLED,
    SAKSHI_MAX_ARTICLES_PER_RUN,
    SAKSHI_MAX_RETRIES,
    SAKSHI_OUTPUT_DIR,
    SAKSHI_OUTPUT_FILE,
    SAKSHI_REQUEST_DELAY_SECONDS,
    SAKSHI_TAG_URL,
    SAKSHI_TIMEOUT_SECONDS,
    SAKSHI_TITLE_SELECTOR,
    SAKSHI_USER_AGENT,
    SKIP_URL_SUBSTRINGS,
    TRANSIENT_HTTP_STATUSES,
    _float_env,
    _int_env,
    _truthy,
)
