"""Legacy shim — re-exports from collectors.sakshi.config."""
# ruff: noqa: F401,F403

from collectors.sakshi.config import *  # noqa: F401,F403
from collectors.sakshi.config import (
    BASE_DIR,
    DATA_DIR,
    SAKSHI_ENABLED,
    SAKSHI_TAG_URL,
    SAKSHI_BASE_URL,
    SAKSHI_REQUEST_DELAY_SECONDS,
    SAKSHI_TIMEOUT_SECONDS,
    SAKSHI_MAX_ARTICLES_PER_RUN,
    SAKSHI_MAX_RETRIES,
    SAKSHI_OUTPUT_DIR,
    SAKSHI_OUTPUT_FILE,
    SAKSHI_ARTICLE_PATH,
    SAKSHI_ANALYZER_OUTPUT_DIR,
    SAKSHI_CHECKPOINT_FILE,
    SAKSHI_USER_AGENT,
    SAKSHI_ARTICLE_LINK_SELECTOR,
    SAKSHI_ARTICLE_BODY_SELECTOR,
    SAKSHI_TITLE_SELECTOR,
    TRANSIENT_HTTP_STATUSES,
    NON_RETRYABLE_HTTP_STATUSES,
    SKIP_URL_SUBSTRINGS,
    _truthy,
    _float_env,
    _int_env,
)
